import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { PhotoModePage } from "@/lib/enums";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Images, ArrowRight } from "lucide-react";
const PhotoPreview = ({ photos, setCurrentPage, paperType, }) => {
    return (_jsx("div", { className: "h-screen mono-gradient flex items-center justify-center p-4 overflow-hidden", children: _jsxs(Card, { className: "glass-card max-w-2xl w-full max-h-full", children: [_jsx(CardHeader, { className: "pb-2", children: _jsxs(CardTitle, { className: "flex items-center gap-2 text-lg", children: [_jsx(Images, { className: "w-5 h-5" }), "Photo Preview"] }) }), _jsxs(CardContent, { className: "space-y-4 max-h-96 overflow-y-auto", children: [photos.length > 0 ? (_jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("h3", { className: "text-base font-semibold text-mono-900", children: "Captured Photos" }), _jsxs(Badge, { variant: "secondary", className: "text-xs", children: [photos.length, " photos"] })] }), _jsx("div", { className: "grid grid-cols-2 gap-2 max-h-48 overflow-y-auto", children: photos.map((photo, index) => (_jsxs("div", { className: "flex items-center justify-between p-2 bg-white rounded-lg border border-mono-200", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-8 h-8 bg-mono-100 rounded-lg flex items-center justify-center", children: _jsx(Images, { className: "w-4 h-4 text-mono-600" }) }), _jsxs("div", { children: [_jsx("div", { className: "font-medium text-mono-900 text-xs truncate", children: photo.name }), _jsxs("div", { className: "text-xs text-mono-600", children: [Math.round(photo.size / 1024), " KB"] })] })] }), _jsxs(Badge, { variant: "outline", className: "text-xs", children: ["Photo ", index + 1] })] }, index))) })] })) : (_jsxs("div", { className: "text-center py-6", children: [_jsx(Images, { className: "w-12 h-12 mx-auto mb-3 text-mono-400" }), _jsx("p", { className: "text-mono-600 text-sm", children: "No photos captured yet." })] })), _jsx("div", { className: "text-center pt-2", children: _jsxs(Button, { onClick: () => setCurrentPage(PhotoModePage.SelectFilterPage), className: "bg-mono-900 hover:bg-mono-800 text-white px-6", children: ["Continue to Filters", _jsx(ArrowRight, { className: "w-4 h-4 ml-2" })] }) })] })] }) }));
};
export default PhotoPreview;
