import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Camera, Film } from "lucide-react";
const Home = () => {
    const navigate = useNavigate();
    return (_jsx("div", { className: "min-h-screen mono-gradient flex flex-col items-center justify-center p-6", children: _jsxs("div", { className: "max-w-4xl w-full", children: [_jsx("div", { className: "text-center mb-12 animate-fade-in", children: _jsxs("div", { className: "mb-8", children: [_jsx("div", { className: "w-24 h-24 mx-auto mb-6 rounded-full bg-mono-900 flex items-center justify-center", children: _jsx(Camera, { className: "w-12 h-12 text-white" }) }), _jsx("h1", { className: "text-6xl font-bold text-mono-900 mb-4 tracking-tight", children: "Photobooth" }), _jsx("div", { className: "w-24 h-1 bg-mono-900 mx-auto mb-6" }), _jsx("p", { className: "text-xl text-mono-600 font-medium", children: "Choose your experience" })] }) }), _jsxs("div", { className: "grid md:grid-cols-2 gap-8 max-w-2xl mx-auto", children: [_jsx(Card, { className: "glass-card hover:shadow-2xl transition-all duration-300 group cursor-pointer animate-slide-up", children: _jsxs(CardContent, { className: "p-8 text-center", children: [_jsx("div", { className: "w-16 h-16 mx-auto mb-6 rounded-full bg-mono-100 flex items-center justify-center group-hover:bg-mono-900 transition-colors duration-300", children: _jsx(Camera, { className: "w-8 h-8 text-mono-900 group-hover:text-white transition-colors duration-300" }) }), _jsx("h3", { className: "text-2xl font-bold text-mono-900 mb-3", children: "Photo Mode" }), _jsx("p", { className: "text-mono-600 mb-6 leading-relaxed", children: "Capture beautiful moments with customizable layouts and filters" }), _jsx(Button, { onClick: () => navigate("/photo"), className: "w-full bg-mono-900 hover:bg-mono-800 text-white font-semibold py-3 px-6 rounded-lg transition-all duration-300", children: "Start Session" })] }) }), _jsx(Card, { className: "glass-card hover:shadow-2xl transition-all duration-300 group cursor-pointer animate-slide-up [animation-delay:100ms]", children: _jsxs(CardContent, { className: "p-8 text-center", children: [_jsx("div", { className: "w-16 h-16 mx-auto mb-6 rounded-full bg-mono-100 flex items-center justify-center group-hover:bg-mono-900 transition-colors duration-300", children: _jsx(Film, { className: "w-8 h-8 text-mono-900 group-hover:text-white transition-colors duration-300" }) }), _jsx("h3", { className: "text-2xl font-bold text-mono-900 mb-3", children: "Flipbook Mode" }), _jsx("p", { className: "text-mono-600 mb-6 leading-relaxed", children: "Create animated flipbook memories with sequential captures" }), _jsx(Button, { onClick: () => navigate("/flipbook"), className: "w-full bg-mono-900 hover:bg-mono-800 text-white font-semibold py-3 px-6 rounded-lg transition-all duration-300", children: "Create Flipbook" })] }) })] }), _jsx("div", { className: "text-center mt-12 animate-fade-in [animation-delay:200ms]", children: _jsx("p", { className: "text-mono-500 text-sm font-medium", children: "Select a mode to begin your photo session" }) })] }) }));
};
export default Home;
