name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install wine for electron-builder
        run: sudo apt-get update && sudo apt-get install -y wine64

      - name: Install dependencies
        run: bun install

      - name: Build app and electron
        run: bun run build:exe

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: photobooth-release
          path: release/
